### ISSUE TITLE
It's way too easy to lose whole database

### ISSUE THREAD

**Issue by scibi** [debops/ansible-postgresql_server#29]
I've just lost my database. I've lost it by running `debops -l my.host.name` to make some minor changes in system configuration (like adding new users). I was too lazy to specify needed tags ;). Fortunately it was a test environment and there is `autopostgresqlbackup` running everyday.

It was my mistake but maybe it's possible to make this role safer?

I needed to install backported PostgreSQL 9.6 on Jessie. So I've configured following variables:

```yaml
postgresql__preferred_version: '9.6'
postgresql_server__preferred_version: '9.6'
postgresql__base_packages:
  - 'postgresql-client-9.6'
postgresql_server__base_packages:
  - 'postgresql-9.6'
  - 'postgresql-client-9.6'
  - 'postgresql-contrib-9.6'

postgresql_server__apt_preferences__dependent_list:
  - package: 'postgresql postgresql-* libpq5 libpq-dev'
    backports: [ 'jessie' ]
    reason: 'Version parity with Debian Stretch'
    role: 'debops.postgresql_server'

postgresql__apt_preferences__dependent_list:
  - package: 'libpq5 libpq-dev'
    backports: [ 'jessie' ]
    reason: 'Version parity with Debian Stretch'
    role: 'debops.postgresql_server'
```

It worked fine for few weeks. But when I run `postgresql_server` role again this task could not find `postgres` package:

```yaml
- name: Check if database server is installed
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'postgresql' | grep -v '^$'
  register: postgresql_server__register_installed
  changed_when: False
  failed_when: False
```

Main PostgreSQL cluster was recreated on every role run because of this. Adding `postgresql` to `postgresql_server__base_packages` solved the problem.
