### ISSUE TITLE
"Start PostgreSQL clusters when not started" task does not get executed on Ubuntu trusty

### ISSUE THREAD

**Issue by glowskir** [debops/ansible-postgresql_server#8]
Ansible 1.9.4
Ubuntu 14.04 LTS

Sample playbook:

example.yml

``` YAML

 hosts: dbservers
  remote_user: user
  sudo: yes
  sudo_user: root

  roles:
    - { role: debops.postgresql_server }
```

ansible-playbook example.yml

"Start PostgreSQL clusters when not started" does not execute which causes futher tasks to fail. I would debug this myself but I'm new to Ansible. Any ideas?

**Comment by drybjed** [comment]
You might need to run the `debops.core` role which provides a legacy `ansible_local.init` fact - it was used before Ansible had an equivalent fact, and will be most likely replaced in the future.

You might also think about upgrading Ansible to `2.0.0.1` version.

**Comment by drybjed** [comment]
The role works as expected when on the `master` branch, I'll relese a new version after changes from https://github.com/debops/ansible-postgresql_server/pull/35 are merged. I'm closing this issue so that it doesn't block the merge of the DebOps roles into unified `git` repository.

**Comment by scosist** [comment]
Don't mean to post on a closed issue, but I ran into a failure on this task for a Debian host. I checked the logs to find the postgresql service failed due to `FATAL:  could not load server certificate file "/etc/pki/realms/host/default.crt": No such file or directory`. I noticed the host directory didn't exist but there were certificates in the domain directory at the same sub-directory level. Checking the `postgresql_server` role led me to using the following to get the task to run successfully.
```
postgresql_server__cluster_main:
  - name: 'main'
    port: '5432'
...(hba settings)
    pki_realm: 'domain'
```
I wondered if this shouldn't be necessary and the default role settings should just work? Or perhaps I should be specifying a pki realm elsewhere?

Note: `ansible_local.pki.realm` is set to `'host'` (even though, `ansible_local.pki.known_realms` is set to `'[ "domain" ]'`) which I believe is what triggered the failure on this task.
